import { Activity, ArrowLeft, Copy, Plus, Radio, Send, Trash2 } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { HubConnectionBuilder } from '@microsoft/signalr';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, Navigate, Route, Routes, useParams } from 'react-router-dom';
import { api } from './api'; import type { Endpoint, ReplayResult, RequestDetail, RequestSummary } from './types';

const hookUrl=(slug:string)=>`${location.origin}/hooks/${slug}/`;
const errorText=(e:unknown)=>e instanceof Error?e.message:'The request could not be completed.';
function App(){return <Routes><Route path="/" element={<EndpointList/>}/><Route path="/endpoints/:id" element={<Workspace/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}

export function EndpointList(){
 const qc=useQueryClient(); const [name,setName]=useState(''); const [slug,setSlug]=useState('');
 const list=useQuery({queryKey:['endpoints'],queryFn:api.endpoints});
 const create=useMutation({mutationFn:api.createEndpoint,onSuccess:()=>{setName('');setSlug('');qc.invalidateQueries({queryKey:['endpoints']})}});
 function submit(e:FormEvent){e.preventDefault();create.mutate({name,slug})}
 return <main className="shell"><header className="mast"><div><p className="eyebrow">LOCAL REQUEST LAB</p><h1>Webhook Studio</h1><p>Catch the signal. Inspect every byte. Replay with intent.</p></div><div className="safety"><Radio size={18}/><span>Local development only<br/><small>Do not expose to the public internet</small></span></div></header>
 <section className="create-panel"><div><h2>Create a receiving endpoint</h2><p>Give the source a memorable name and URL-safe slug.</p></div><form onSubmit={submit}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={80} placeholder="Stripe sandbox"/></label><label>Slug<input value={slug} onChange={e=>setSlug(e.target.value)} required maxLength={80} pattern="[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?" placeholder="stripe-sandbox"/></label><button disabled={create.isPending}><Plus size={18}/>{create.isPending?'Creating…':'Create endpoint'}</button></form>{create.isError&&<p className="error" role="alert">{errorText(create.error)}</p>}</section>
 <section aria-labelledby="endpoints-heading"><div className="section-title"><h2 id="endpoints-heading">Endpoints</h2><span>{list.data?.length??0} active</span></div>{list.isLoading?<Status text="Loading endpoints…"/>:list.isError?<Status error text={errorText(list.error)}/>:list.data?.length===0?<Status text="No endpoints yet. Create one above, then send your first webhook."/>:<div className="endpoint-grid">{list.data?.map(ep=><article key={ep.id} className="endpoint-card"><Link to={`/endpoints/${ep.id}`}><span className="live-dot"/><h3>{ep.name}</h3><code>/hooks/{ep.slug}/</code></Link><div className="card-actions"><button className="secondary" onClick={()=>navigator.clipboard.writeText(hookUrl(ep.slug))}><Copy size={16}/>Copy URL</button><button className="danger-icon" aria-label={`Delete ${ep.name}`} onClick={()=>confirm(`Delete ${ep.name} and its requests?`)&&api.deleteEndpoint(ep.id).then(()=>qc.invalidateQueries({queryKey:['endpoints']}))}><Trash2 size={17}/></button></div></article>)}</div>}</section></main>
}

export function Workspace(){
 const {id=''}=useParams(); const qc=useQueryClient(); const endpoint=useQuery({queryKey:['endpoint',id],queryFn:()=>api.endpoint(id)}); const requests=useQuery({queryKey:['requests',id],queryFn:()=>api.requests(id)}); const [selected,setSelected]=useState<string>();
 useEffect(()=>{if(!selected&&requests.data?.items[0])setSelected(requests.data.items[0].id)},[requests.data,selected]);
 useEffect(()=>{if(!id)return; const c=new HubConnectionBuilder().withUrl('/hubs/requests').withAutomaticReconnect().build(); c.on('RequestCaptured',(item:RequestSummary)=>{qc.setQueryData<{items:RequestSummary[];total:number}>(['requests',id],old=>({items:[item,...(old?.items.filter(x=>x.id!==item.id)??[])],total:(old?.total??0)+1}));setSelected(item.id)}); c.start().then(()=>c.invoke('JoinEndpoint',id)).catch(()=>{}); return()=>{void c.stop()}},[id,qc]);
 if(endpoint.isLoading)return <Status text="Opening workspace…"/>; if(endpoint.isError)return <Status error text={errorText(endpoint.error)}/>;
 return <main className="workspace"><header className="workspace-head"><Link to="/" className="back"><ArrowLeft size={18}/>Endpoints</Link><div><h1>{endpoint.data?.name}</h1><button className="url-copy" onClick={()=>navigator.clipboard.writeText(hookUrl(endpoint.data!.slug))}><code>{hookUrl(endpoint.data!.slug)}</code><Copy size={16}/></button></div><span className="listening"><span className="live-dot"/>Listening</span></header><div className="work-grid"><aside className="request-rail"><div className="rail-title"><h2>Request stream</h2><span>{requests.data?.total??0}</span></div>{requests.isLoading?<Status text="Loading requests…"/>:requests.data?.items.length===0?<Status text="Waiting for a webhook. Send any HTTP request to the URL above."/>:<ul>{requests.data?.items.map(r=><li key={r.id}><button className={selected===r.id?'selected':''} onClick={()=>setSelected(r.id)}><span className={`method method-${r.method.toLowerCase()}`}>{r.method}</span><span className="request-path">{r.pathAndQuery}</span><time>{new Date(r.receivedAtUtc).toLocaleTimeString()}</time><small>{r.bodySize} B</small></button></li>)}</ul>}</aside><section className="detail-pane">{selected?<RequestDetailPanel id={selected}/>:<Status text="Select a request to inspect its details."/>}</section></div></main>
}

export function RequestDetailPanel({id}:{id:string}){
 const detail=useQuery({queryKey:['request',id],queryFn:()=>api.request(id)}); const [target,setTarget]=useState(''); const replay=useMutation({mutationFn:()=>api.replay(id,target)});
 const body=useMemo(()=>detail.data?decodeBody(detail.data):null,[detail.data]);
 if(detail.isLoading)return <Status text="Reading request…"/>; if(detail.isError)return <Status error text={errorText(detail.error)}/>; const r=detail.data!;
 const curl=toCurl(r); const info=toInfo(r,body?.text);
 return <div className="detail"><div className="detail-head"><div><span className={`method method-${r.method.toLowerCase()}`}>{r.method}</span><h2>{r.pathAndQuery}</h2><p>{new Date(r.receivedAtUtc).toLocaleString()} · {r.remoteIp||'Unknown IP'} · {r.bodySize} bytes</p></div><div className="copy-group"><button className="secondary" onClick={()=>navigator.clipboard.writeText(info)}><Copy size={16}/>Copy info</button><button className="secondary" onClick={()=>navigator.clipboard.writeText(curl)}><Copy size={16}/>Copy curl</button></div></div><DataBlock title="Headers"><dl className="headers">{Object.entries(r.headers).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v.join(', ')}</dd></div>)}</dl></DataBlock><DataBlock title="Body">{body?.binary?<p className="muted">Binary content · {r.bodySize} bytes</p>:<pre>{body?.text||'Empty body'}</pre>}</DataBlock><section className="replay"><div><h3>Replay request</h3><p>Send the original method, body, and content headers to a local target.</p></div><form onSubmit={e=>{e.preventDefault();replay.mutate()}}><label>Target URL<input type="url" value={target} onChange={e=>setTarget(e.target.value)} required placeholder="http://localhost:9000/receive"/></label><button disabled={replay.isPending}><Send size={17}/>{replay.isPending?'Replaying…':'Replay'}</button></form>{replay.data&&<ReplayFeedback result={replay.data}/>} {replay.isError&&<p role="alert" className="error">Replay failed: {errorText(replay.error)}</p>}</section></div>
}
function ReplayFeedback({result}:{result:ReplayResult}){return <p role="status" className={result.succeeded?'success':'error'}>{result.succeeded?`Received HTTP ${result.statusCode} in ${result.durationMs} ms`:`Replay failed after ${result.durationMs} ms: ${result.error}`}</p>}
function DataBlock({title,children}:{title:string;children:React.ReactNode}){return <section className="data-block"><h3>{title}</h3>{children}</section>}
function Status({text,error=false}:{text:string;error?:boolean}){return <div className={`status ${error?'error':''}`} role={error?'alert':'status'}><Activity size={20}/><p>{text}</p></div>}
function decodeBody(r:RequestDetail){try{const bytes=Uint8Array.from(atob(r.bodyBase64),c=>c.charCodeAt(0));const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(r.contentType?.includes('json'))try{return{text:JSON.stringify(JSON.parse(text),null,2),binary:false}}catch{}return{text,binary:false}}catch{return{text:'',binary:true}}}
function toInfo(r:RequestDetail,body=''){return `${r.method} ${r.pathAndQuery}\nReceived: ${r.receivedAtUtc}\n${Object.entries(r.headers).map(([k,v])=>`${k}: ${v.join(', ')}`).join('\n')}\n\n${body}`}
function toCurl(r:RequestDetail){const headers=Object.entries(r.headers).filter(([k])=>!['host','content-length'].includes(k.toLowerCase())).map(([k,v])=>`-H '${k}: ${v.join(', ')}'`).join(' ');const body=decodeBody(r);return `curl -X ${r.method} ${headers} ${body.binary||!body.text?'':`--data-raw '${body.text.split("'").join("'\\''")}'`} 'TARGET_URL'`}
export default App;
