import { Activity,ArrowLeft,Check,ChevronLeft,ChevronRight,Clipboard,Copy,Download,GitCompare,Import,Menu,Moon,Plus,Radio,RotateCcw,Search,Send,Settings,Sun,Trash2,X } from 'lucide-react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { HubConnectionBuilder,HubConnectionState } from '@microsoft/signalr';
import { FormEvent,useEffect,useMemo,useRef,useState } from 'react';
import { Link,Navigate,Route,Routes,useNavigate,useParams,useSearchParams } from 'react-router-dom';
import { api } from './api'; import type { DiffItem,Endpoint,Filters,ReplayResult,RequestDetail,RequestSummary } from './types';

const hookUrl=(slug:string)=>`${location.origin}/hooks/${slug}/`; const errorText=(e:unknown)=>e instanceof Error?e.message:'The request could not be completed.';
const defaults={responseStatusCode:200,responseContentType:'application/json',responseBody:'{"received":true}',responseDelayMs:0,retentionLimit:500};
function App(){return <Routes><Route path="/" element={<EndpointList/>}/><Route path="/endpoints/:id" element={<Workspace/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}

export function EndpointList(){const qc=useQueryClient();const nav=useNavigate();const [name,setName]=useState('');const [slug,setSlug]=useState('');const list=useQuery({queryKey:['endpoints'],queryFn:api.endpoints});const create=useMutation({mutationFn:api.createEndpoint,onSuccess:e=>{qc.invalidateQueries({queryKey:['endpoints']});nav(`/endpoints/${e.id}`)}});return <main className="landing"><header><div><p className="eyebrow">LOCAL REQUEST LAB</p><h1>Webhook Studio</h1><p>Receive, inspect, compare, and replay webhook traffic without leaving your machine.</p></div><ThemeButton/></header><section className="create-panel"><div><h2>Create endpoint</h2><p>Start a durable local inbox for one webhook source.</p></div><form onSubmit={(e:FormEvent)=>{e.preventDefault();create.mutate({name,slug})}}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={80}/></label><label>Slug<input value={slug} onChange={e=>setSlug(e.target.value)} required pattern="[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?"/></label><button disabled={create.isPending}><Plus size={17}/>{create.isPending?'Creating…':'Create endpoint'}</button></form>{create.isError&&<Feedback error text={errorText(create.error)}/>}</section><section><div className="section-title"><h2>Endpoints</h2><span>{list.data?.length??0}</span></div>{list.isLoading?<Status text="Loading endpoints…"/>:list.data?.length?<div className="endpoint-grid">{list.data.map(e=><Link className="endpoint-card" key={e.id} to={`/endpoints/${e.id}`}><span className="pulse-dot"/><strong>{e.name}</strong><code>/hooks/{e.slug}/</code><small>{e.retentionLimit} request retention</small></Link>)}</div>:<Status text="No endpoints yet. Create one above."/>}</section></main>}

export function Workspace(){const {id=''}=useParams();const qc=useQueryClient();const [params,setParams]=useSearchParams();const [connection,setConnection]=useState<'connecting'|'connected'|'disconnected'|'failed'>('connecting');const [newId,setNewId]=useState('');const [mobileNav,setMobileNav]=useState(false);const endpoint=useQuery({queryKey:['endpoint',id],queryFn:()=>api.endpoint(id)});const endpoints=useQuery({queryKey:['endpoints'],queryFn:api.endpoints});const filters:Filters={page:Number(params.get('page')||1),method:params.get('method')||'',statusCategory:params.get('status')||'',from:params.get('from')||'',to:params.get('to')||'',search:params.get('q')||''};const selected=params.get('request')||'';const compare=params.getAll('compare');const requests=useQuery({queryKey:['requests',id,filters],queryFn:()=>api.requests(id,filters)});
 const update=(changes:Record<string,string>)=>setParams(old=>{const n=new URLSearchParams(old);Object.entries(changes).forEach(([k,v])=>v?n.set(k,v):n.delete(k));return n});
 useEffect(()=>{if(!selected&&requests.data?.items[0])update({request:requests.data.items[0].id})},[requests.data]);
 useEffect(()=>{const c=new HubConnectionBuilder().withUrl('/hubs/requests').withAutomaticReconnect().build();c.onreconnecting(()=>setConnection('connecting'));c.onreconnected(async()=>{setConnection('connected');await qc.invalidateQueries({queryKey:['requests',id]})});c.onclose(()=>setConnection('failed'));c.on('RequestCaptured',(item:RequestSummary)=>{setNewId(item.id);qc.invalidateQueries({queryKey:['requests',id]})});c.start().then(()=>c.invoke('JoinEndpoint',id)).then(()=>setConnection('connected')).catch(()=>setConnection('failed'));return()=>{if(c.state!==HubConnectionState.Disconnected)void c.stop()}},[id,qc]);
 if(endpoint.isLoading)return <Status text="Opening workspace…"/>;if(endpoint.isError)return <Status text={errorText(endpoint.error)} error/>;const ep=endpoint.data!;
 return <main className="studio"><header className="studio-head"><button className="icon-button mobile-only" aria-label="Open endpoint navigation" onClick={()=>setMobileNav(!mobileNav)}><Menu/></button><div><h1>{ep.name}</h1><button className="copy-url" onClick={()=>navigator.clipboard.writeText(hookUrl(ep.slug))}><code>{hookUrl(ep.slug)}</code><Copy size={15}/></button></div><Connection status={connection}/><ThemeButton/></header><div className="studio-grid"><aside className={`endpoint-nav ${mobileNav?'open':''}`}><div className="nav-head"><Link to="/"><ArrowLeft size={16}/>Endpoints</Link><button className="icon-button mobile-only" aria-label="Close endpoint navigation" onClick={()=>setMobileNav(false)}><X/></button></div><nav aria-label="Endpoints">{endpoints.data?.map(e=><Link key={e.id} className={e.id===id?'active':''} to={`/endpoints/${e.id}`}><span className="pulse-dot"/>{e.name}</Link>)}</nav><div className="local-warning"><Radio size={16}/><span>Local only<br/><small>Do not expose publicly</small></span></div></aside><section className="request-column"><FiltersBar value={filters} onChange={update}/><div className="stream-head"><strong>Requests</strong><span>{requests.data?.total??0}</span></div>{requests.isLoading?<Status text="Loading requests…"/>:requests.data?.items.length?<ul className="request-list">{requests.data.items.map(r=><RequestRow key={r.id} item={r} selected={selected===r.id} fresh={newId===r.id} compare={compare.includes(r.id)} onSelect={()=>update({request:r.id})} onCompare={()=>{const next=compare.includes(r.id)?compare.filter(x=>x!==r.id):[...compare,r.id].slice(-2);const n=new URLSearchParams(params);n.delete('compare');next.forEach(x=>n.append('compare',x));setParams(n)}}/>)}</ul>:<Status text="No requests match these filters."/>}<Pagination page={filters.page} total={requests.data?.total||0} onPage={p=>update({page:String(p)})}/></section><section className="inspector">{compare.length===2?<ComparePanel endpointId={id} ids={compare as [string,string]} onClose={()=>{const n=new URLSearchParams(params);n.delete('compare');setParams(n)}}/>:selected?<RequestDetailPanel id={selected}/>:<Status text="Select a request to inspect it."/>}</section></div><WorkspaceActions endpoint={ep}/><div className="sr-live" aria-live="polite">{newId?'New request received.':''}</div></main>}

function FiltersBar({value,onChange}:{value:Filters;onChange:(x:Record<string,string>)=>void}){return <div className="filters"><label className="search"><Search size={15}/><span className="sr-only">Search requests</span><input value={value.search} onChange={e=>onChange({q:e.target.value,page:'1'})} placeholder="Path, query, or body"/></label><select aria-label="HTTP method" value={value.method} onChange={e=>onChange({method:e.target.value,page:'1'})}><option value="">All methods</option>{['GET','POST','PUT','PATCH','DELETE'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Status category" value={value.statusCategory} onChange={e=>onChange({status:e.target.value,page:'1'})}><option value="">All status</option>{[2,3,4,5].map(x=><option key={x} value={x}>{x}xx</option>)}</select><label><span>From</span><input type="datetime-local" value={value.from} onChange={e=>onChange({from:e.target.value,page:'1'})}/></label><label><span>To</span><input type="datetime-local" value={value.to} onChange={e=>onChange({to:e.target.value,page:'1'})}/></label></div>}
function RequestRow({item,selected,fresh,compare,onSelect,onCompare}:{item:RequestSummary;selected:boolean;fresh:boolean;compare:boolean;onSelect:()=>void;onCompare:()=>void}){return <li className={fresh?'fresh':''}><button className={selected?'selected':''} onClick={onSelect}><span className={`method method-${item.method.toLowerCase()}`}>{item.method}</span><span className="request-path">{item.pathAndQuery}</span><time>{new Date(item.receivedAtUtc).toLocaleTimeString()}</time><small>{item.responseStatusCode} · {item.bodySize} B</small></button><button className={`compare-check ${compare?'checked':''}`} aria-label={`${compare?'Remove from':'Add to'} comparison`} onClick={onCompare}>{compare?<Check size={15}/>:<GitCompare size={15}/>}</button></li>}
function Pagination({page,total,onPage}:{page:number;total:number;onPage:(x:number)=>void}){if(total<=25)return null;return <div className="pagination"><button disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft/>Previous</button><span>Page {page}</span><button disabled={page*25>=total} onClick={()=>onPage(page+1)}>Next<ChevronRight/></button></div>}

export function RequestDetailPanel({id}:{id:string}){const detail=useQuery({queryKey:['request',id],queryFn:()=>api.request(id)});const [target,setTarget]=useState('');const [expanded,setExpanded]=useState(false);const [feedback,setFeedback]=useState('');const replay=useMutation({mutationFn:()=>api.replay(id,target),onSuccess:r=>setFeedback(r.succeeded?`Received HTTP ${r.statusCode} in ${r.durationMs} ms`:`Replay failed: ${r.error}`)});if(detail.isLoading)return <Status text="Reading request…"/>;if(detail.isError)return <Status text={errorText(detail.error)} error/>;const r=detail.data!;const body=decodeBody(r);const visible=body.text.length>10000&&!expanded?body.text.slice(0,10000):body.text;return <div className="detail"><div className="detail-head"><div><span className={`method method-${r.method.toLowerCase()}`}>{r.method}</span><h2>{r.pathAndQuery}</h2><p>{new Date(r.receivedAtUtc).toLocaleString()} · {r.remoteIp||'Unknown IP'} · {r.bodySize} bytes</p></div><div className="toolbar"><CopyButton text={toInfo(r,body.text)} label="Copy info"/><CopyButton text={toCurl(r)} label="Copy curl"/><a className="button secondary" href={`/api/requests/${id}/export?format=har`} download><Download size={16}/>HAR</a></div></div><DataBlock title="Headers"><dl className="headers">{Object.entries(r.headers).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v.join(', ')}</dd></div>)}</dl></DataBlock><DataBlock title="Body">{body.binary?<p>Binary content · {r.bodySize} bytes</p>:<><pre>{visible||'Empty body'}</pre>{body.text.length>10000&&<button className="secondary" onClick={()=>setExpanded(!expanded)}>{expanded?'Collapse':'Show full body'}</button>}</>}</DataBlock><section className="replay"><h3>Replay request</h3><form onSubmit={e=>{e.preventDefault();replay.mutate()}}><label>Target URL<input type="url" value={target} onChange={e=>setTarget(e.target.value)} required placeholder="http://localhost:9000/receive"/></label><button disabled={replay.isPending}><Send size={16}/>{replay.isPending?'Replaying…':'Replay'}</button></form>{feedback&&<Feedback text={feedback} error={!replay.data?.succeeded}/>}</section></div>}
function ComparePanel({endpointId,ids,onClose}:{endpointId:string;ids:[string,string];onClose:()=>void}){const q=useQuery({queryKey:['compare',...ids],queryFn:()=>api.compare(endpointId,ids[0],ids[1])});return <div className="compare-panel"><div className="panel-title"><div><p className="eyebrow">STRUCTURED DIFF</p><h2>Request comparison</h2></div><button className="icon-button" aria-label="Close comparison" onClick={onClose}><X/></button></div>{q.isLoading?<Status text="Comparing requests…"/>:q.data?.differences.length?<table><thead><tr><th>Meaning</th><th>Field</th><th>Left</th><th>Right</th></tr></thead><tbody>{q.data.differences.map((d,i)=><tr key={i}><td><span className={`diff-kind ${d.kind}`}>{d.kind}</span></td><td><code>{d.path}</code></td><td><code>{d.left??'—'}</code></td><td><code>{d.right??'—'}</code></td></tr>)}</tbody></table>:<Status text="These requests are identical in compared fields."/>}</div>}

function WorkspaceActions({endpoint}:{endpoint:Endpoint}){const qc=useQueryClient();const [open,setOpen]=useState(false);const [notice,setNotice]=useState('');const file=useRef<HTMLInputElement>(null);const settingsButton=useRef<HTMLButtonElement>(null);const closeSettings=()=>{setOpen(false);requestAnimationFrame(()=>settingsButton.current?.focus())};const clear=useMutation({mutationFn:()=>api.clear(endpoint.id),onSuccess:r=>{setNotice(`Cleared ${r.deleted} requests.`);qc.invalidateQueries({queryKey:['requests',endpoint.id]})}});return <div className="workspace-actions"><button ref={settingsButton} className="secondary" onClick={()=>setOpen(true)}><Settings size={16}/>Endpoint settings</button><a className="button secondary" href={`/api/endpoints/${endpoint.id}/export`} download><Download size={16}/>Export JSON</a><button className="secondary" onClick={()=>file.current?.click()}><Import size={16}/>Import JSON</button><input ref={file} hidden type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(f)try{const r=await api.importPackage(endpoint.id,f);setNotice(`Imported ${r.imported} requests.`);qc.invalidateQueries({queryKey:['requests',endpoint.id]})}catch(x){setNotice(errorText(x))}}}/><button className="danger" onClick={()=>confirm('Clear all requests for this endpoint? This cannot be undone.')&&clear.mutate()}><Trash2 size={16}/>Clear requests</button>{notice&&<div className="toast" role="status">{notice}</div>}{open&&<SettingsDialog endpoint={endpoint} onClose={closeSettings}/>}</div>}
function SettingsDialog({endpoint,onClose}:{endpoint:Endpoint;onClose:()=>void}){const qc=useQueryClient();const dialog=useRef<HTMLDivElement>(null);const first=useRef<HTMLInputElement>(null);const [form,setForm]=useState({...endpoint});const save=useMutation({mutationFn:()=>api.settings(endpoint.id,form),onSuccess:e=>{qc.setQueryData(['endpoint',endpoint.id],e);onClose()}});useEffect(()=>{first.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=[...dialog.current!.querySelectorAll<HTMLElement>('button,input,textarea')].filter(x=>!x.hasAttribute('disabled'));if(!items.length)return;const edge=e.shiftKey?items[0]:items[items.length-1];if(document.activeElement===edge){e.preventDefault();(e.shiftKey?items[items.length-1]:items[0])?.focus()}}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[onClose]);return <div className="dialog-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="settings-title" className="dialog"><div className="panel-title"><h2 id="settings-title">Endpoint settings</h2><button className="icon-button" aria-label="Close settings" onClick={onClose}><X/></button></div><form onSubmit={e=>{e.preventDefault();save.mutate()}}><label>Status code<input ref={first} type="number" min="100" max="599" value={form.responseStatusCode} onChange={e=>setForm({...form,responseStatusCode:+e.target.value})}/></label><label>Content-Type<input value={form.responseContentType} onChange={e=>setForm({...form,responseContentType:e.target.value})}/></label><label>Response body<textarea maxLength={65536} value={form.responseBody} onChange={e=>setForm({...form,responseBody:e.target.value})}/></label><label>Delay (ms)<input type="number" min="0" max="10000" value={form.responseDelayMs} onChange={e=>setForm({...form,responseDelayMs:+e.target.value})}/></label><label>Retain requests<input type="number" min="10" max="10000" value={form.retentionLimit} onChange={e=>setForm({...form,retentionLimit:+e.target.value})}/></label><div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setForm({...form,...defaults})}><RotateCcw size={16}/>Restore defaults</button><button disabled={save.isPending}>{save.isPending?'Saving…':'Save settings'}</button></div>{save.isError&&<Feedback error text={errorText(save.error)}/>}</form></div></div>}

function ThemeButton(){const [dark,setDark]=useState(()=>localStorage.theme!=='light');useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.theme=dark?'dark':'light'},[dark]);return <button className="icon-button" aria-label={`Use ${dark?'light':'dark'} theme`} onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button>}
function Connection({status}:{status:string}){const labels:{[k:string]:string}={connecting:'Connecting',connected:'Connected',disconnected:'Disconnected',failed:'Reconnect failed'};return <span className={`connection ${status}`}><span/>{labels[status]}</span>}
function CopyButton({text,label}:{text:string;label:string}){const [done,setDone]=useState(false);return <button className="secondary" onClick={async()=>{await navigator.clipboard.writeText(text);setDone(true);setTimeout(()=>setDone(false),1500)}}>{done?<Check size={16}/>:<Clipboard size={16}/>} {done?'Copied':label}</button>}
function DataBlock({title,children}:{title:string;children:React.ReactNode}){return <section className="data-block"><h3>{title}</h3>{children}</section>}
function Status({text,error=false}:{text:string;error?:boolean}){return <div className={`status ${error?'error':''}`} role={error?'alert':'status'}><Activity size={18}/><p>{text}</p></div>}
function Feedback({text,error=false}:{text:string;error?:boolean}){return <p className={`feedback ${error?'error':'success'}`} role={error?'alert':'status'}>{error?<X size={15}/>:<Check size={15}/>} {text}</p>}
function decodeBody(r:RequestDetail){try{const bytes=Uint8Array.from(atob(r.bodyBase64),c=>c.charCodeAt(0));const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(r.contentType?.includes('json'))try{return{text:JSON.stringify(JSON.parse(text),null,2),binary:false}}catch{}return{text,binary:false}}catch{return{text:'',binary:true}}}
function toInfo(r:RequestDetail,body=''){return `${r.method} ${r.pathAndQuery}\nReceived: ${r.receivedAtUtc}\n${Object.entries(r.headers).filter(([k])=>!['authorization','cookie'].includes(k.toLowerCase())).map(([k,v])=>`${k}: ${v.join(', ')}`).join('\n')}\n\n${body}`}
function toCurl(r:RequestDetail){const headers=Object.entries(r.headers).filter(([k])=>!['host','content-length','authorization','cookie'].includes(k.toLowerCase())).map(([k,v])=>`-H '${k}: ${v.join(', ')}'`).join(' ');const body=decodeBody(r);return `curl -X ${r.method} ${headers} ${body.binary||!body.text?'':`--data-raw '${body.text.split("'").join("'\\''")}'`} 'TARGET_URL'`}
export default App;
